server:
  port: 7772
  servlet:
    context-path: /spring-boot2
spring:
  datasource:
    platform: H2
    name: boot2-demo
    url: jdbc:h2:mem:boot2-demo
  jpa:
    hibernate:
      ddl-auto: create
        
  h2:
    console:
      enabled: true  
      settings:
        web-allow-others: true
    


debug: false


springfox:
  documentation:
    swagger: 
      v2:
        path: /api-docs